### ISSUE TITLE
Dialog exits immediately, if the `enter` transition is not finished

### ISSUE THREAD

**Issue by Ninjars** [composablehorizons/compose-unstyled#30] opened 2024-10-16 10:56 UTC
### Problem
As a user of this library, I expect that when the Dialog is closed I would see the exit animations on the library components within the Dialog. However, the Dialog immediately disappears once closed, skipping exit animations.

### Detail
Scrim and DialogPanel both accept exit animations. However, when setting the Dialog's DialogState.visible to false the contents composable is immediately removed from the composition and no exit animations are displayed.

Inside Dialog the Modal composable is only included if this condition is met: scope.visibleState.currentState || scope.visibleState.targetState || scope.visibleState.isIdle.not(). This in effect prevents any AnimateVisibility or similar from within those composables to execute when the Dialog as a whole is dismissed.

### Suggestion
One approach to fix this might be to wrap the Modal with an AnimateVisibility instead of the if{} block, where visible equals that same condition, supplying entry and exit animations to Dialog in the same way Scrim and DialogPanel already do, and then the current visibility value could be propagated via the DialogScope or a CompositionLocal for consumption by the Scrim and DialogPanel library components, or by any end-user components.

### Example code
Note that despite long exit animations being registered on both the Scrim and the DialogPanel, neither of those animations are displayed as the entire modal content is immediately removed from the composition when DialogState.visible is set to false.

```
import androidx.compose.animation.core.tween
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import com.composables.core.Dialog
import com.composables.core.DialogPanel
import com.composables.core.Scrim
import com.composables.core.rememberDialogState


@Composable
fun Example() {
    val dialogState = rememberDialogState(initiallyVisible = false)
    Button(
        onClick = { dialogState.visible = !dialogState.visible}
    ) {
        Text(text = "Button")
    }
    Dialog(state = dialogState) {
        Scrim(
            enter = fadeIn(tween(durationMillis = 2000)),
            exit = fadeOut(tween(durationMillis = 5000)),
        )
        DialogPanel(
            enter = fadeIn(tween(durationMillis = 2000)),
            exit = fadeOut(tween(durationMillis = 5000)),
        ) {
            Box(
                contentAlignment = Alignment.Center,
                modifier = Modifier.fillMaxSize(0.5f)
                    .background(Color.Red)
            ) {
                Text(text = "My Dialog Content")
            }
        }
    }
}
```

**Comment by alexstyl** [comment] 2024-10-16 11:33
Thank you for the detailed issue. Will check asap

**Comment by Ninjars** [comment] 2024-10-16 12:57
Thank you - appreciate the aim of this library, and am intending to use this in production soon. Fixing this would be icing on the cake :)

**Comment by alexstyl** [comment] 2024-10-16 16:06
I was able to reproduce it. The reason for this is how `AnimatedVisibility` works. Seems like if you change the visible state while the enter is running, the exit animation is ignored. Simple reproducable:

```kotlin
val visibleState = remember { MutableTransitionState(false) }
    LaunchedEffect(Unit) {
        while (true) {
            visibleState.targetState = visibleState.targetState.not()
            delay(5_000)
        }
    }
    AnimatedVisibility(
        visibleState = visibleState,
        enter = fadeIn(tween(durationMillis = 10_000)),
        exit = fadeOut(tween(durationMillis = 10_000))
    ) {
        Box(Modifier.fillMaxSize().background(Color.Black))
    }
```

It seems like a bug in `AnimatedVisibility` [as described in this issue on the Google Tracker](https://issuetracker.google.com/issues/271675891).

Not sure yet how to tackle this yet.

As a workaround for now, you can have a very short enter duration.

**Comment by alexstyl** [comment] 2024-10-17 11:09
> you just need to keep those elements in the composition - at least until the exit animations have completed.

That's what the code you are sharing does. The `if` condition returns true when transition is visible, or about to be visible. It's how the animations control the composition of the `Modal()`.

---

The only thing that I can imagine that could be causing some issue is the fact that both Scrim and Dialog's AnimatedVisibility is controlled by the same `TransitionState` and their timings could be off.

However, given the bug on `AnimatedVisibility` mentioned above, it won't really fix your issue, even if this is indeed a problem and it gets resolved.

**Comment by Ninjars** [comment] 2024-10-18 09:00
Am I missing something? When the Dialog is visible and then becomes no longer visible, does that condition not mean that the Modal is immediately removed from the composition? Does the `MutableTransitionState` used in `ModalBottomSheetScope.visibleState` remain "not idle" until all the transitions reacting to the change in state have resolved?

> The only thing that I can imagine that could be causing some issue is the fact that both Scrim and Dialog's AnimatedVisibility is controlled by the same TransitionState and their timings could be off.

The exit animation issue with Dialog is present even if there's no Scrim. Just to check, have you tried that example composable out and verified the animation behaviour yourself? It's entirely possible I've missed something with how the library handles animations and there's something else at play, but currently it's felt that you're talking past the issue I've raised.

I'm not convinced that the google bug is the cause of this issue - it's explicitly about not handling exit animations whilst enter animations are active, and I'm exclusively talking about exit animations here, even when there are no enter animations.

**Comment by Ninjars** [comment] 2024-10-18 09:23
I checked against ModalBottomSheet and the same issue doesn't apply; it displays entry and exit animations, including handling a Scrim element with an arbitrary long exit animation. At the root level it's using the same condition checks on its MutableTransitionState, so that's good evidence that that mechanic isn't the issue, looks like I was wrong on that front.

Do you know what is different in the animation handling between the ModalBottomSheet and Dialog?

**Comment by Ninjars** [comment] 2024-10-18 10:08
I went to double-check the Dialog behaviour.

In my project code the Dialog didn't display either enter or exit animations. So to confirm, I pasted the Example composable above into the same place and triggered it instead - and the animations worked, though with that mentioned AnimateVisibility bug that seems to be inconsistent about exit animations whilst an entry animation is active.

So I went through each element of my project implementation and realised: the root of the issue I was seeing was that I was using a `Modifier.layout {}` to position the DialogPanel within my screen. This appears to break completely break animations, and was completely unexpected to me.

I moved the layout modifier to a box wrapping the DialogPanel and I'm now getting the behaviour I expect.

Thank you for your time with this, sorry I didn't narrow down my reproduction steps correctly initially.

**Comment by alexstyl** [comment] 2024-10-18 10:18
No problem. I'm glad you were able to find the cause.

I also checked on my side that there is no problem with using the same `MutableTransitionState` in multiple `AnimatedVisibility`ies. The state changes when all of the animations are complete.

However the google issue will still affect you unless it is resolved, and because of this I will keep this open to track that issue.

**Comment by alexstyl** [comment] 2024-10-18 12:03
Closing this as won't fix.

If someone comes across this bug on Compose, they would need to fix it on their app side.

**Closed** 2024-10-18 12:03 UTC
Labels: bug
