### ISSUE TITLE
ModalBottomSheet doens't like predictive back

### ISSUE THREAD

**Issue by chrisjenx** [composablehorizons/compose-unstyled#46] opened 2024-12-09 05:36 UTC
Predictive back seems to be ignored (or stolen) on the dialog, Esc, back key, dismiss all work, See video:

Version 1.20.0
CMP 1.7.1

https://github.com/user-attachments/assets/9181873e-08d3-45e5-85b1-6bdcf780f70d

**Comment by alexstyl** [comment] 2024-12-09 09:21
Thanks for the report. Could you kindly provide a minimum reproducible project or snippet on how you have wired things?

**Comment by chrisjenx** [comment] 2024-12-09 15:05
I removed the embedded DockedSearchBar and now it works. Seems like it's a relationship between SeaechBar and the gesture.

However, it's fine on the CMP modal. I just reveted back to using that, feel free to close if you can reproduce easily

**Comment by alexstyl** [comment] 2024-12-09 15:16
Cool. Glad to hear it works.

What do you mean by CMP modal? Are you referring to the modals that come with the unstyled library?

**Comment by chrisjenx** [comment] 2024-12-09 17:35
CMP = Compose Multi Platform

**Comment by alexstyl** [comment] 2024-12-10 12:22
Could you share how things are wired? How are you handling the predictive back gesture and where does your DockedSearchBar sit on your layout in relation to the bottom sheet?

**Comment by chrisjenx** [comment] 2024-12-10 15:56
Layout was:

```
ModalBottomSheet() {
  Sheet() {
    DockedSearchBar(
      input = {}, 
    ) {
    }
  }
}
```

I think the Docked or the regular SearchBar steal the gesture? removing them (I changed them too just an InputField and Column now), fixed it, not sure why they don't mind being embedded in the jetbrains ModalBottomSheet

**Comment by alexstyl** [comment] 2024-12-10 16:18
I am not sure if I can reproduce this. I am tried using either sheets (M3 or Unstyled) and the result was the same in both. Pressing back causes the `onExpandedChange` to be called, which it seems to be intended behavior when the `DockedSearchBar()` is `expanded`. This is how the `DockedSearchBar()` works (the code of the composable enables a `BackHandler()` when `expanded` is true).

However, this blocks both back presses (back button), esc, and gesture back. 

This is the code I used:

```kotlin
        androidx.compose.material3.ModalBottomSheet(onDismissRequest = {
            error("OnDismiss called") // <- never called
        }) {
            Column {
                DockedSearchBar(
                    inputField = {
                        TextField("", onValueChange = {})
                    },
                    expanded = true,
                    onExpandedChange = {}
                ) {
                    BasicText("Hello there")
                }

            }
        }

```

However, I am not sure if this is the behavior you saw, as you said that in your case back button and esc worked.

If I am missing something here, do let me know. Otherwise I would have to close this as can't reproduce.

**Closed** 2024-12-10 16:21 UTC
Labels: more info required

**Comment by alexstyl** [comment] 2024-12-11 05:05
Hard to tell.

Curious how you tested that 'Back' and  'Esc' worked. Did you try on different devices or platforms? If yes, which ones?
